# Generated by Django 4.2.4 on 2023-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.CharField(max_length=50),
        ),
    ]
