# Generated by Django 4.2.4 on 2023-08-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_storestatus_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storehours',
            old_name='day_of_week',
            new_name='day',
        ),
    ]
