# Generated by Django 4.2.4 on 2023-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_day_of_week_storehours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehours',
            name='store_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='store_id',
            field=models.CharField(max_length=50),
        ),
    ]
