# Generated by Django 4.2.4 on 2023-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reportstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstatus',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
